Associations
AntonioHincapie/school-library_rb pull request #3
Opened 2022-08-12 20:48 UTC by AntonioHincapie

- Create a class Classroom with the following:
  - @label instance variable, should be initialized in the constructor.
  - Setter and getter for @label (remember about attr_accessor).
- Create the has-many/belongs-to relationship between Classroom and Student. The following should be implemented:
  - Create the has-many side (a classroom has many students).
  - Create the belongs-to side (a student belongs to a classroom).
  - Make sure that when adding a student to a classroom it also sets the classroom for the student.
  - Make sure that when setting the classroom for a student it also adds it to the classroom's students.
- Create a class Book with the following:
  - @title and @author instance variables, should be initialized in the constructor.
  - Setters and getters for instance variables (remember about attr_accessor).
- Create a class Rental with the following:
  - @date instance variable, should be initialized in the constructor.
  - Setter and getter for @date (remember about attr_accessor).
- Create the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental. The following should be implemented:
  - Create the has-many side of Book and Rental (a book has many rentals).
  - Create the belongs-to side of Rental and Book (a rental belongs to a book).
  - Create the has-many side of Person and Rental (a person has many rentals).
  - Create the belongs-to side of Rental and Person (a rental belongs to a person).
  - Modify the constructor of Rental so Book and Person are set in it.

2022-08-12 21:52 UTC, EricMbouwe requested changes
Hi @AntonioHincapie, 

Good job so far 🔥!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🔥🎉
- Linters ✔
- Classes ✔
- PR ✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-12 21:52 UTC, EricMbouwe commented on files/book.rb
> +end
- [ ] A method for adding rentals should be present. It follows the association between books and rentals. Let's add it

2022-08-12 21:52 UTC, EricMbouwe commented on files/person.rb
>    def initialize(age, name, parent_permission: true)
- [ ] A method for adding rentals should be present. It follows the association between persons and rentals. Let's add it

2022-08-13 16:04 UTC, codepantha requested changes
# STATUS: REQUIRED CHANGES ♻️ 

## Hi @AntonioHincapie 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/YVpIaYgJ3lpMk/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit messages
✔️ No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-13 16:04 UTC, codepantha commented on files/book.rb
> +end
- [ ] You have done well by attempting to create the `add_rental` method, however, your implementation of the relationship between the `Book` class and `Rental` class is not entirely finished. Please reference this [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship)

2022-08-13 16:04 UTC, codepantha commented on files/person.rb
> +    @rentals.push(rental)
- [ ] You have done well by attempting to make the required changes, however, your implementation of the relationship between the `Person` class and `Rental` class is not entirely finished. Please reference this [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship)

2022-08-13 16:07 UTC, AntonioHincapie commented on files/person.rb
> +    @rentals.push(rental)
Hi @codepantha 
Can you please be more specific about the change that you are requiring?
I have already checked the article and I don't find the missing part.
Thanks

2022-08-13 16:48 UTC, codepantha commented on files/person.rb
> +    @rentals.push(rental)
Okay. For instance, you'd have to do something like this 👇 in order to achieve that `has-many` relationship
```
def add_rental(person, date)
  Rental.new(date, book, self)
end
```

2022-08-13 16:49 UTC, AntonioHincapie commented on files/person.rb
> +    @rentals.push(rental)
Sure, I already found the solution.

2022-08-13 16:54 UTC, ahmetbozaci approved these changes
# 🥳 🎉🥇 💯  💥 🎆 🎈 STATUS: APPROVED 🥳 🎉  🥇  💯  💥   🎆 🎈 🎉 
![](https://media.giphy.com/media/3pZipqyo1sqHDfJGtz/giphy.gif)


@AntonioHincapie  ✋🏼 
#### Your project is excellent. 🎉 I approve of it. There is nothing else to say other than... it's time to merge it. You can submit this project on your dashboard.
___ 

### 💯 Highlights 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️

___ 

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
___

### Cheers and Happy coding! 💻 👏
![aproved](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2022-08-13 16:55 UTC, merged